# Generated by Django 4.1.3 on 2022-12-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMER', '0002_salespersonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespersonmodel',
            name='SAL_ID_MDL',
            field=models.CharField(max_length=10),
        ),
    ]
