# Generated by Django 4.1.3 on 2022-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMER', '0003_alter_salespersonmodel_sal_id_mdl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUS_TYPE_MDL', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'CUSTOMER TYPE',
                'verbose_name_plural': 'CUSTOMER TYPES',
            },
        ),
    ]
