# Generated by Django 4.1.3 on 2022-12-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUSTOMER', '0004_customertypemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinputmodel',
            name='CUS_TYP_MDL',
            field=models.CharField(max_length=50),
        ),
    ]
